name: "Linux"

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup C++ Environment
      run: |
        sudo apt update && sudo apt install -y g++ libomp-dev libopenblas-dev libmkl-dev intel-mkl python3-pip python3-virtualenv
        
#    - name: Clone and install AOCL
#      run: |
#        git clone https://github.com/amd/blis
#        cd blis
#        ./configure --enable-cblas --blas-int-size=64 --enable-threading=openmp --enable-shared generic
#        make -j && sudo make install && make check -j
        
    - name: Install Gtest
      run: |
        git clone https://github.com/google/googletest.git
        cd googletest
        mkdir build && cd build
        cmake .. -DBUILD_GMOCK=OFF
        make -j && sudo make install
      
    - name: Git Clone TTV Repo
      run: |
        cd ${GITHUB_WORKSPACE}
        git clone https://github.com/bassoy/ttv.git

    - name: Build and Run Tests (Intel MKL)
      run: |
        cd ttv/test
        make clean && make -j BLAS_FLAG=MKL
        ./bin/main

    - name: Build and Run Tests (OpenBLAS)
      run: |
        cd ttv/test
        make clean && make -j BLAS_FLAG=OPENBLAS
        ./bin/main

#    - name: Build and Run Tests (BLIS)
#      run: |
#        cd ttv/test
#        make clean && make -j BLAS_FLAG=BLIS
#        ./bin/main
        
    - name: Build and Run Python Wrapper Tests (OpenBLAS)
      run: |
        cd ttv/ttvpy
        virtualenv ~/env-ttv
        source ~/env-ttv/bin/activate
        pip install -e .
        cd tests
        python3 -m unittest discover -v
        deactivate
